# Generated by Django 4.1 on 2022-08-31 09:23

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartman_naziv', models.CharField(max_length=100)),
                ('apartman_cijena', models.FloatField()),
                ('apartman_vlasnik', models.CharField(max_length=100)),
                ('apartman_smjestaji', models.IntegerField()),
                ('apartman_lokacija', models.CharField(max_length=100)),
                ('apartman_odobren', models.BooleanField(default=False)),
                ('apartman_sadrzaj', models.TextField()),
                ('apartman_glavna_slika', models.ImageField(blank=True, null=True, upload_to=main.models.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('apartman', models.CharField(max_length=10)),
                ('sadrzaj', models.TextField()),
                ('ocjena', models.IntegerField()),
            ],
        ),
    ]
