# Generated by Django 4.1 on 2022-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartman',
            name='apartman_glavna_slika',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
